/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedPagosRouteImport } from './routes/_authenticated/pagos'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedArticulosRouteImport } from './routes/_authenticated/articulos'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes_.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagosRoute = AuthenticatedPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArticulosRoute = AuthenticatedArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes_/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/articulos': typeof AuthenticatedArticulosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/pagos': typeof AuthenticatedPagosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/articulos': typeof AuthenticatedArticulosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/pagos': typeof AuthenticatedPagosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/articulos': typeof AuthenticatedArticulosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/pagos': typeof AuthenticatedPagosRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/clientes_/$id': typeof AuthenticatedClientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/articulos'
    | '/clientes'
    | '/pagos'
    | '/reportes'
    | '/reservas'
    | '/clientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/articulos'
    | '/clientes'
    | '/pagos'
    | '/reportes'
    | '/reservas'
    | '/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/articulos'
    | '/_authenticated/clientes'
    | '/_authenticated/pagos'
    | '/_authenticated/reportes'
    | '/_authenticated/reservas'
    | '/_authenticated/clientes_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagos': {
      id: '/_authenticated/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AuthenticatedPagosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articulos': {
      id: '/_authenticated/articulos'
      path: '/articulos'
      fullPath: '/articulos'
      preLoaderRoute: typeof AuthenticatedArticulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes_/$id': {
      id: '/_authenticated/clientes_/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArticulosRoute: typeof AuthenticatedArticulosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedPagosRoute: typeof AuthenticatedPagosRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArticulosRoute: AuthenticatedArticulosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedPagosRoute: AuthenticatedPagosRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
